# Generated by Django 4.2.5 on 2023-09-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'наименование',
                'verbose_name_plural': 'наименования',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                ('description', models.CharField(max_length=100, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='изображение')),
                ('category', models.CharField(max_length=250, verbose_name='категория')),
                ('purchase_price', models.IntegerField(verbose_name='цена за покупку')),
                ('date_of_creation', models.DateTimeField()),
                ('last_modified_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'наименование',
                'verbose_name_plural': 'наименования',
                'ordering': ('name',),
            },
        ),
    ]
