# Generated by Django 4.2.5 on 2023-10-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_possibilities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='possibilities',
            options={'verbose_name': 'возможность', 'verbose_name_plural': 'возможности'},
        ),
    ]
